import Head from 'next/head'
import Card from '@layouts/Card'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className='h-screen w-screen flex items-center'>
        <Card style={"mx-auto"} />
      </section>
    </>
  )
}
